/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaswingdev.form;

import com.sun.jdi.connect.spi.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author PC
 */
public class Form_Stagiaire extends javax.swing.JPanel {
    
    private final ConnectDB dbConnection; // Declare a private field for ConnectDB
    private DefaultTableModel tableModel;

    /**
     * Creates new form Form_Inscription
     */ 
    public Form_Stagiaire() {
        initComponents();
        
        initializeTableModel();
        displayDataInTable();
        addTableClickListener();
        
        dbConnection = new ConnectDB();
        dbConnection.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Modifier = new javax.swing.JButton();
        NomStg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableStg = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ajouter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Impr = new javax.swing.JButton();
        IdStg = new javax.swing.JTextField();
        Filiere = new javax.swing.JComboBox<>();
        Supp = new javax.swing.JButton();
        PrenomStg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Promotion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Modifier.setBackground(new java.awt.Color(0, 51, 255));
        Modifier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Modifier.setText("Modifier");
        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierMouseClicked(evt);
            }
        });
        Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierActionPerformed(evt);
            }
        });
        add(Modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 150, 50));

        NomStg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomStgActionPerformed(evt);
            }
        });
        add(NomStg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Promotion:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        TableStg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableStg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableStgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableStg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 500, 510));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("SYSTÈME D'INFORMATION DES ÉTUDIANTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        Ajouter.setBackground(new java.awt.Color(51, 255, 0));
        Ajouter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ajouter.setText("Insérer");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });
        add(Ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 150, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nom:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        Impr.setBackground(new java.awt.Color(0, 204, 255));
        Impr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Impr.setText("Imprimer");
        Impr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprActionPerformed(evt);
            }
        });
        add(Impr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 150, 50));
        add(IdStg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, -1));

        Filiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TSDI", "TSGE", "TGI", "OpAd" }));
        add(Filiere, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 150, -1));

        Supp.setBackground(new java.awt.Color(255, 0, 51));
        Supp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Supp.setText("Supprimer");
        Supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppActionPerformed(evt);
            }
        });
        add(Supp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 150, 50));
        add(PrenomStg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Prenom:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Groupe IPIRNET");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 204));
        jLabel9.setText("Donnee Stagiaire");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 204));
        jLabel10.setText("Formulaire");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        Promotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromotionActionPerformed(evt);
            }
        });
        add(Promotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("/");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Filiere:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("YYYY");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("YYYY");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 150, 50));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Table
    private void initializeTableModel() {
        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");
        tableModel.addColumn("Nom");
        tableModel.addColumn("Prenom");
        tableModel.addColumn("Filiere");
        tableModel.addColumn("Promotion");
        TableStg.setModel(tableModel);
    }

    private void updateTableModel() {
        tableModel.setRowCount(0); // Clear existing rows
        ConnectDB con = ConnectDB.getcon();
        con.connect();

        try {
            String sqlQuery = "SELECT * FROM Stagaire";
            ResultSet rs = con.executeQuery(sqlQuery);

            while (rs.next()) {
                Object[] rowData = {
                    rs.getInt("IdStg"),
                    rs.getString("NomStg"),
                    rs.getString("PrenomStg"),
                    rs.getString("Filiere"),
                    rs.getString("Promotion")
                };
                tableModel.addRow(rowData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_Stagiaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void addTableClickListener() {
        TableStg.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = TableStg.getSelectedRow();
                if (selectedRow != -1) { // Ensure a row is selected
                    Object idStgObj = TableStg.getValueAt(selectedRow, 0);
                    Object nomStgObj = TableStg.getValueAt(selectedRow, 1);
                    Object prenomStgObj = TableStg.getValueAt(selectedRow, 2);
                    Object filiereObj = TableStg.getValueAt(selectedRow, 3);
                    Object promotionObj = TableStg.getValueAt(selectedRow, 4);
                    
                    // Check for null values before converting to string
                    String idStg = idStgObj != null ? idStgObj.toString() : "";
                    String nomStg = nomStgObj != null ? nomStgObj.toString() : "";
                    String prenomStg = prenomStgObj != null ? prenomStgObj.toString() : "";
                    String filiere = filiereObj != null ? filiereObj.toString() : "";
                    String promotion = promotionObj != null ? promotionObj.toString() : "";
                    
                    IdStg.setText(idStg);
                    NomStg.setText(nomStg);
                    PrenomStg.setText(prenomStg);
                    Filiere.setSelectedItem(filiere);
                    Promotion.setText(promotion);
                }
            }
        });
    }
    
     private void displayDataInTable() {
        ConnectDB con = ConnectDB.getcon();
        con.connect();

        try {
            String sqlQuery = "SELECT * FROM Stagaire";
            ResultSet rs = con.executeQuery(sqlQuery);


            while (rs.next()) {
                Object[] rowData = {
                    rs.getInt("IdStg"),
                    rs.getString("NomStg"),
                    rs.getString("PrenomStg"),
                    rs.getString("Filiere"),
                    rs.getString("Promotion")
                };
                 tableModel.addRow(rowData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Form_Stagiaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     // Table END
     
    private void ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMouseClicked

    }//GEN-LAST:event_ModifierMouseClicked
    
    //Modifier Stagiaire
    private void ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierActionPerformed
            
            StagiaireBean cb = new StagiaireBean();
    
            // Parse the integer value for IdStg
            int idStg;
            try {
                idStg = Integer.parseInt(IdStg.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Erreur : Veuillez entrer un entier pour Id.", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if parsing fails
            }
            cb.setIdStg(idStg);

            cb.setNomStg(NomStg.getText());
            cb.setPrenomStg(PrenomStg.getText());
            cb.setFiliere(Filiere.getSelectedItem().toString());
            cb.setPromotion(Promotion.getText());
            
            ConnectDB con = ConnectDB.getcon(); 
            try {
                con.connect();
                con.modifierstg(cb); // Call the modifierstg method
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erreur lors de la modification du stagiaire : " + ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Form_Stagiaire.class.getName()).log(Level.SEVERE, null, ex);
            }
            updateTableModel(); 
    }//GEN-LAST:event_ModifierActionPerformed

    private void NomStgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomStgActionPerformed
    }//GEN-LAST:event_NomStgActionPerformed

    private void TableStgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableStgMouseClicked
    }//GEN-LAST:event_TableStgMouseClicked

    //Ajouter Stagiaire
    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed

            StagiaireBean cb=new StagiaireBean();
            int idStg;
        try { 
            idStg = Integer.parseInt(IdStg.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erreur : Veuillez entrer un entier pour IdStg.", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method if parsing fails
        }
        cb.setIdStg(idStg);
            cb.setNomStg(NomStg.getText());
            cb.setPrenomStg(PrenomStg.getText());
            cb.setFiliere(Filiere.getSelectedItem().toString());
            cb.setPromotion(Promotion.getText());

            ConnectDB con = ConnectDB.getcon();
                try {
            con.connect();
            con.ajouterstg(cb);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout du stagiaire : " + ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Form_Stagiaire.class.getName()).log(Level.SEVERE, null, ex);

        }
         updateTableModel();       
    }//GEN-LAST:event_AjouterActionPerformed

    private void ImprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprActionPerformed
         try {
        // Load the JasperReport template
        JasperDesign jasdi = JRXmlLoader.load("C:\\Users\\PC\\JaspersoftWorkspace\\MyReports\\Stagiaire.jrxml");

        // Set the SQL query to select all records from the Stagaire table
        String sql = "SELECT * FROM Stagaire";
        JRDesignQuery newQuery = new JRDesignQuery();
        newQuery.setText(sql);
        jasdi.setQuery(newQuery);

        // Compile the JasperReport template
        JasperReport js = JasperCompileManager.compileReport(jasdi);

        // Provide a database connection (replace 'con' with your actual Connection object)
        ConnectDB con = ConnectDB.getcon();

        // Fill the JasperReport with data
        JasperPrint jd = JasperFillManager.fillReport(js, null, dbConnection.con);

        // Show the report in a JasperViewer
        JasperViewer.viewReport(jd, false);

    } catch (JRException ex) {
        Logger.getLogger(Form_Stagiaire.class.getName()).log(Level.SEVERE, null, ex);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_ImprActionPerformed

    //Supprimer (Delete) Stagiaire
    private void SuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppActionPerformed
            String idToDelete = IdStg.getText(); // Get ID from text field or wherever it's stored

            ConnectDB con = ConnectDB.getcon();
            try {
                con.deleteStagiaire(idToDelete); // Call the delete method
                updateTableModel(); // Refresh the table after deletion
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erreur lors de la suppression du stagiaire : " + ex.getMessage(), "Erreur SQL", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Form_Stagiaire.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_SuppActionPerformed

    private void PromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromotionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PromotionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private javax.swing.JComboBox<String> Filiere;
    private javax.swing.JTextField IdStg;
    private javax.swing.JButton Impr;
    private javax.swing.JButton Modifier;
    private javax.swing.JTextField NomStg;
    private javax.swing.JTextField PrenomStg;
    private javax.swing.JTextField Promotion;
    private javax.swing.JButton Supp;
    private javax.swing.JTable TableStg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
